/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2 */

#ifndef PB_COMMAND_PB_H_INCLUDED
#define PB_COMMAND_PB_H_INCLUDED
#include "pb.h"
#include "header.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _ServoGroup {
    ServoGroup_DROP_PADA = 0
} ServoGroup;

typedef enum _ServoState {
    ServoState_OPEN = 0,
    ServoState_CLOSE = 1
} ServoState;

typedef enum _FlightStabilizationMethods {
    FlightStabilizationMethods_NONE = 0,
    FlightStabilizationMethods_WEIGHTED_AVERAGE = 1
} FlightStabilizationMethods;

/* Struct definitions */
typedef struct _ActuateGroup {
    ServoGroup group;
    ServoState state;
} ActuateGroup;

typedef struct _ActuateServo {
    uint32_t servo_number;
    pb_size_t which_arg;
    union {
        ServoState state;
        int32_t value;
    } arg;
} ActuateServo;

typedef struct _FlightStabilization {
    FlightStabilizationMethods method;
    uint32_t args;
} FlightStabilization;

typedef struct _ServoConfig {
    uint32_t index;
    uint32_t open;
    uint32_t close;
    ServoGroup group;
    ServoState state;
} ServoConfig;

typedef struct _Command {
    bool has_header;
    Header header;
    bool reset_processor;
    pb_callback_t actuate_group;
    bool has_flight_stabilization;
    FlightStabilization flight_stabilization;
    pb_callback_t actuate_servo;
    pb_callback_t servo_config;
} Command;


/* Helper constants for enums */
#define _ServoGroup_MIN ServoGroup_DROP_PADA
#define _ServoGroup_MAX ServoGroup_DROP_PADA
#define _ServoGroup_ARRAYSIZE ((ServoGroup)(ServoGroup_DROP_PADA+1))

#define _ServoState_MIN ServoState_OPEN
#define _ServoState_MAX ServoState_CLOSE
#define _ServoState_ARRAYSIZE ((ServoState)(ServoState_CLOSE+1))

#define _FlightStabilizationMethods_MIN FlightStabilizationMethods_NONE
#define _FlightStabilizationMethods_MAX FlightStabilizationMethods_WEIGHTED_AVERAGE
#define _FlightStabilizationMethods_ARRAYSIZE ((FlightStabilizationMethods)(FlightStabilizationMethods_WEIGHTED_AVERAGE+1))


/* Initializer values for message structs */
#define Command_init_default                     {false, Header_init_default, 0, {{NULL}, NULL}, false, FlightStabilization_init_default, {{NULL}, NULL}, {{NULL}, NULL}}
#define ActuateGroup_init_default                {_ServoGroup_MIN, _ServoState_MIN}
#define FlightStabilization_init_default         {_FlightStabilizationMethods_MIN, 0}
#define ActuateServo_init_default                {0, 0, {_ServoState_MIN}}
#define ServoConfig_init_default                 {0, 0, 0, _ServoGroup_MIN, _ServoState_MIN}
#define Command_init_zero                        {false, Header_init_zero, 0, {{NULL}, NULL}, false, FlightStabilization_init_zero, {{NULL}, NULL}, {{NULL}, NULL}}
#define ActuateGroup_init_zero                   {_ServoGroup_MIN, _ServoState_MIN}
#define FlightStabilization_init_zero            {_FlightStabilizationMethods_MIN, 0}
#define ActuateServo_init_zero                   {0, 0, {_ServoState_MIN}}
#define ServoConfig_init_zero                    {0, 0, 0, _ServoGroup_MIN, _ServoState_MIN}

/* Field tags (for use in manual encoding/decoding) */
#define ActuateGroup_group_tag                   1
#define ActuateGroup_state_tag                   2
#define ActuateServo_servo_number_tag            1
#define ActuateServo_state_tag                   2
#define ActuateServo_value_tag                   3
#define FlightStabilization_method_tag           1
#define FlightStabilization_args_tag             2
#define ServoConfig_index_tag                    1
#define ServoConfig_open_tag                     2
#define ServoConfig_close_tag                    3
#define ServoConfig_group_tag                    4
#define ServoConfig_state_tag                    5
#define Command_header_tag                       1
#define Command_reset_processor_tag              2
#define Command_actuate_group_tag                3
#define Command_flight_stabilization_tag         4
#define Command_actuate_servo_tag                5
#define Command_servo_config_tag                 6

/* Struct field encoding specification for nanopb */
#define Command_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   SINGULAR, BOOL,     reset_processor,   2) \
X(a, CALLBACK, REPEATED, MESSAGE,  actuate_group,     3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  flight_stabilization,   4) \
X(a, CALLBACK, REPEATED, MESSAGE,  actuate_servo,     5) \
X(a, CALLBACK, REPEATED, MESSAGE,  servo_config,      6)
#define Command_CALLBACK pb_default_field_callback
#define Command_DEFAULT NULL
#define Command_header_MSGTYPE Header
#define Command_actuate_group_MSGTYPE ActuateGroup
#define Command_flight_stabilization_MSGTYPE FlightStabilization
#define Command_actuate_servo_MSGTYPE ActuateServo
#define Command_servo_config_MSGTYPE ServoConfig

#define ActuateGroup_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    group,             1) \
X(a, STATIC,   SINGULAR, UENUM,    state,             2)
#define ActuateGroup_CALLBACK NULL
#define ActuateGroup_DEFAULT NULL

#define FlightStabilization_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    method,            1) \
X(a, STATIC,   SINGULAR, UINT32,   args,              2)
#define FlightStabilization_CALLBACK NULL
#define FlightStabilization_DEFAULT NULL

#define ActuateServo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   servo_number,      1) \
X(a, STATIC,   ONEOF,    ENUM,     (arg,state,arg.state),   2) \
X(a, STATIC,   ONEOF,    INT32,    (arg,value,arg.value),   3)
#define ActuateServo_CALLBACK NULL
#define ActuateServo_DEFAULT NULL

#define ServoConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   index,             1) \
X(a, STATIC,   SINGULAR, UINT32,   open,              2) \
X(a, STATIC,   SINGULAR, UINT32,   close,             3) \
X(a, STATIC,   SINGULAR, UENUM,    group,             4) \
X(a, STATIC,   SINGULAR, UENUM,    state,             5)
#define ServoConfig_CALLBACK NULL
#define ServoConfig_DEFAULT NULL

extern const pb_msgdesc_t Command_msg;
extern const pb_msgdesc_t ActuateGroup_msg;
extern const pb_msgdesc_t FlightStabilization_msg;
extern const pb_msgdesc_t ActuateServo_msg;
extern const pb_msgdesc_t ServoConfig_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Command_fields &Command_msg
#define ActuateGroup_fields &ActuateGroup_msg
#define FlightStabilization_fields &FlightStabilization_msg
#define ActuateServo_fields &ActuateServo_msg
#define ServoConfig_fields &ServoConfig_msg

/* Maximum encoded size of messages (where known) */
/* Command_size depends on runtime parameters */
#define ActuateGroup_size                        4
#define FlightStabilization_size                 8
#define ActuateServo_size                        17
#define ServoConfig_size                         22

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
