/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.2 */

#include "sensors.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(ImuData, ImuData, AUTO)


PB_BIND(GpsData, GpsData, AUTO)


PB_BIND(EnviroData, EnviroData, AUTO)


PB_BIND(BatteryData, BatteryData, AUTO)


PB_BIND(RadioData, RadioData, AUTO)



