/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2 */

#ifndef PB_TELEMETRY_PB_H_INCLUDED
#define PB_TELEMETRY_PB_H_INCLUDED
#include "pb.h"
#include "header.pb.h"
#include "sensors.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _Telemetry {
    bool has_header;
    Header header;
    bool has_imu;
    ImuData imu;
    bool has_gps;
    GpsData gps;
    bool has_enviro;
    EnviroData enviro;
    bool has_battery;
    BatteryData battery;
    bool has_plane_radio;
    RadioData plane_radio;
    bool has_gnd_radio;
    RadioData gnd_radio;
    uint32_t response_to;
} Telemetry;


/* Initializer values for message structs */
#define Telemetry_init_default                   {false, Header_init_default, false, ImuData_init_default, false, GpsData_init_default, false, EnviroData_init_default, false, BatteryData_init_default, false, RadioData_init_default, false, RadioData_init_default, 0}
#define Telemetry_init_zero                      {false, Header_init_zero, false, ImuData_init_zero, false, GpsData_init_zero, false, EnviroData_init_zero, false, BatteryData_init_zero, false, RadioData_init_zero, false, RadioData_init_zero, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Telemetry_header_tag                     1
#define Telemetry_imu_tag                        2
#define Telemetry_gps_tag                        3
#define Telemetry_enviro_tag                     4
#define Telemetry_battery_tag                    5
#define Telemetry_plane_radio_tag                6
#define Telemetry_gnd_radio_tag                  7
#define Telemetry_response_to_tag                8

/* Struct field encoding specification for nanopb */
#define Telemetry_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  imu,               2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  gps,               3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  enviro,            4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  battery,           5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  plane_radio,       6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  gnd_radio,         7) \
X(a, STATIC,   SINGULAR, UINT32,   response_to,       8)
#define Telemetry_CALLBACK NULL
#define Telemetry_DEFAULT NULL
#define Telemetry_header_MSGTYPE Header
#define Telemetry_imu_MSGTYPE ImuData
#define Telemetry_gps_MSGTYPE GpsData
#define Telemetry_enviro_MSGTYPE EnviroData
#define Telemetry_battery_MSGTYPE BatteryData
#define Telemetry_plane_radio_MSGTYPE RadioData
#define Telemetry_gnd_radio_MSGTYPE RadioData

extern const pb_msgdesc_t Telemetry_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Telemetry_fields &Telemetry_msg

/* Maximum encoded size of messages (where known) */
#define Telemetry_size                           239

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
