/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.2 */

#include "command.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Command, Command, AUTO)


PB_BIND(ActuateGroup, ActuateGroup, AUTO)


PB_BIND(FlightStabilization, FlightStabilization, AUTO)


PB_BIND(ActuateServo, ActuateServo, AUTO)


PB_BIND(ServoConfig, ServoConfig, AUTO)






