/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.2 */

#include "message.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Message, Message, AUTO)


PB_BIND(Pitot, Pitot, AUTO)


PB_BIND(IMU, IMU, AUTO)


PB_BIND(GPS, GPS, AUTO)


PB_BIND(Enviro, Enviro, AUTO)


PB_BIND(Battery, Battery, AUTO)


PB_BIND(Glider, Glider, AUTO)


PB_BIND(Servo, Servo, AUTO)









